openapi: 3.0.3
info:
  title: Credential Persistence API
  description: API endpoints for credential persistence and account recovery
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/auth
    description: Development server (Better Auth endpoints)

paths:
  /sign-in:
    post:
      summary: Sign in with email and password
      description: Authenticates a user with email and password credentials from the database
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
                password:
                  type: string
                  format: password
                  example: SecurePass123!
      responses:
        '200':
          description: Successful sign in
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      email:
                        type: string
                      name:
                        type: string
                      emailVerified:
                        type: boolean
                  session:
                    type: object
                    properties:
                      token:
                        type: string
                  error:
                    type: object
                    nullable: true
        '400':
          description: Invalid credentials
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Too many sign-in attempts. Please try again later.

  /sign-up:
    post:
      summary: Create a new account
      description: Registers a new user with email and password. Sends verification email.
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password, name]
              properties:
                email:
                  type: string
                  format: email
                  example: newuser@example.com
                password:
                  type: string
                  format: password
                  minLength: 8
                  example: SecurePass123!
                name:
                  type: string
                  example: John Doe
      responses:
        '200':
          description: Account created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      email:
                        type: string
                      name:
                        type: string
                      emailVerified:
                        type: boolean
                        example: false
                  error:
                    type: object
                    nullable: true
        '400':
          description: Invalid input or email already exists
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /sign-out:
    post:
      summary: Sign out current user
      description: Ends the current session and clears authentication cookies
      tags:
        - Authentication
      responses:
        '200':
          description: Successfully signed out
        '401':
          description: No active session

  /get-session:
    get:
      summary: Get current session
      description: Returns the currently authenticated user's session data
      tags:
        - Authentication
      responses:
        '200':
          description: Session data returned
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      email:
                        type: string
                      name:
                        type: string
                      emailVerified:
                        type: boolean
                  session:
                    type: object
                    nullable: true
        '401':
          description: No active session

  /send-reset-email:
    post:
      summary: Request password reset
      description: Sends a password reset email to the user's registered email address
      tags:
        - Password Recovery
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email]
              properties:
                email:
                  type: string
                  format: email
                  example: user@example.com
      responses:
        '200':
          description: Reset email sent (or email not found - returns same response for security)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: If an account exists with this email, a reset link has been sent.
        '429':
          description: Too many requests (rate limit exceeded)
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Too many requests. Please try again later.

  /reset-password/{token}:
    page:
      summary: Reset password form
      description: Displays the password reset form (frontend route)
      tags:
        - Password Recovery
    get:
      summary: Validate reset token
      description: Validates that the reset token is valid and not expired
      parameters:
        - name: token
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Token is valid, show reset form
        '400':
          description: Invalid or expired token
    post:
      summary: Submit new password
      description: Updates the user's password with the new value
      parameters:
        - name: token
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [password]
              properties:
                password:
                  type: string
                  format: password
                  minLength: 8
                  example: NewSecurePass456!
      responses:
        '200':
          description: Password updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Password updated successfully. You can now sign in.
        '400':
          description: Invalid token or password
      put:
      summary: Alternative method for password reset
      description: Same as POST, included for client compatibility
      parameters:
        - name: token
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [password]
              properties:
                password:
                  type: string
                  format: password
                  minLength: 8
      responses:
        '200':
          description: Password updated successfully
        '400':
          description: Invalid token or password

  /verify-email:
    get:
      summary: Verify email address
      description: Verifies the user's email using the token from the verification email
      tags:
        - Email Verification
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
          description: Verification token from email
      responses:
        '302':
          description: Redirect to dashboard after successful verification
        '400':
          description: Invalid or expired token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /jwks:
    get:
      summary: JSON Web Key Set
      description: Returns the public keys for JWT signature verification
      tags:
        - Authentication
      responses:
        '200':
          description: JWKS response
          content:
            application/json:
              schema:
                type: object
                properties:
                  keys:
                    type: array
                    items:
                      type: object
                      properties:
                        alg:
                          type: string
                          example: EdDSA
                        kty:
                          type: string
                          example: OKP
                        kid:
                          type: string
                        x:
                          type: string
                        crv:
                          type: string
                          example: Ed25519

components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
          format: email
        name:
          type: string
        emailVerified:
          type: boolean
        createdAt:
          type: string
          format: date-time

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      description: JWT token authentication
