# Dapr Kubernetes Secret Store Component
# Type: secretstores.kubernetes
# Purpose: Fetch secrets from Kubernetes secrets (no credentials in code)
#
# Usage in backend:
#   from dapr.clients import DaprClient
#   async with DaprClient() as client:
#       secret = await client.get_secret(
#           store_name="kubernetes-secrets",
#           key="DATABASE_URL"
#       )
#
# Available Secrets:
#   - DATABASE_URL: PostgreSQL connection string
#   - BETTER_AUTH_SECRET: JWT signing secret for Better Auth
#   - OPENAI_API_KEY: OpenAI API key for chatbot
#   - DAPR_API_TOKEN: Dapr API token (optional)
#
# Kubernetes Secret Creation:
#   kubectl create secret generic todo-secrets \
#     --from-literal=database-url="postgresql://..." \
#     --from-literal=better-auth-secret="..." \
#     --from-literal=openai-api-key="..." \
#     -n todo-app
#
# See: https://docs.dapr.io/operations/components/setup-secret-store/supported-secret-stores/kubernetes-secret-store/

apiVersion: dapr.io/v1
kind: Component
metadata:
  name: kubernetes-secrets
  namespace: todo-app
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
    # No additional metadata needed for Kubernetes secret store
    # Secrets are accessed via Kubernetes secret name and key
    []
scopes:
  todo-backend:
    kinds:
      - type: SecretStore
        name: kubernetes-secrets
    # Backend needs all secrets
    allowedSecrets: ["DATABASE_URL", "BETTER_AUTH_SECRET", "OPENAI_API_KEY"]
  todo-frontend:
    kinds:
      - type: SecretStore
        name: kubernetes-secrets
    # Frontend only needs Better Auth secret (for client-side validation)
    allowedSecrets: ["BETTER_AUTH_SECRET"]
